### ISSUE TITLE
Filters, all the filters

### ISSUE THREAD

**Issue by chrishutchinson** [times/cardkit-v2#20]
Snap.svg has some nice filters, would be good to allow those to be editable (e.g. sepia, saturation, blur etc.)

**Comment by aendrew** [comment]
Oooh, InstaCardKit!

**Comment by chrishutchinson** [comment]
Added initial support in commit c2ec9add5c683096204404d7a15cdc6a00c96220 for grayscale, sepia, blur, inverted and saturation filters.
